### ISSUE TITLE
Replace `clickhouse_rs_cityhash_sys` with pure Rust crate `cityhash-rs`

### ISSUE THREAD

**Issue by blind-oracle** [ClickHouse/clickhouse-rs#107]
`clickhouse_rs_cityhash_sys` is a C++ binding and thus requires a C++ compiler to build which sometimes is a problem.

**Comment by blind-oracle** [comment]
@loyd 

Thanks! Currently I have a working fork using `cityhash-rs` with version 1.0.2, will try to make a PR. The only weird thing is that the hash that this crate produces has high/low 64 bits swapped in contrast to what we get from the C version, so I had to swap them back.

Changes are minor: https://github.com/loyd/clickhouse.rs/commit/beba19192da6c50884a0b8f5797fda53185d8844

**Comment by loyd** [comment]
Let's include a modified cityhash in the repository, giving us both more control and security.

**Comment by loyd** [comment]
Thanks for your commit, I used it in related PR

**Comment by blind-oracle** [comment]
Thanks! Sorry i've been on holidays to go through it myself
