### ISSUE TITLE
Condiitional insert types

### ISSUE THREAD

**Issue by AdvaithD** [ClickHouse/clickhouse-rs#129]
I have a rust binary where I want to conditionally make the inserts "async inserts" depending on a specific environment variable. Wondering whats the best way to do this.

Thanks!

**Comment by loyd** [comment]
We have [the example for async insertions](https://github.com/ClickHouse/clickhouse-rs/blob/master/examples/async_insert.rs), so you can read that specific environment variable and configure the client depending on it.

**Comment by AdvaithD** [comment]
Thanks @loyd - i missed seeing that in the docs.
