### ISSUE TITLE
Support new JSON data type

### ISSUE THREAD

**Issue by slvrtrn** [ClickHouse/clickhouse-rs#144]
https://clickhouse.com/docs/en/sql-reference/data-types/newjson

**Comment by loyd** [comment]
Do you have information on how it is encoded?

**Comment by slvrtrn** [comment]
@loyd, when [this](https://github.com/ClickHouse/ClickHouse/pull/70288) is released, it should be possible to just use a string.

**Comment by slvrtrn** [comment]
Closing it for now, as we merged #171. It can be re-opened if we decide to implement full de/serialization of this type.
