### ISSUE TITLE
Batch Insert Support

### ISSUE THREAD

**Issue by barkhayot** [ClickHouse/clickhouse-rs#167]
### Description 
The implementation of batch insert functionality in the Rust SDK for ClickHouse, similar to the Go SDK. Batch inserts allow for the insertion of multiple rows in a single query, which is highly beneficial for optimizing performance in high-throughput scenarios.

### Use Case:
It would be handling real-time data ingestion, where thousands of inserts are happening concurrently. The ability to batch multiple rows into a single query would reduce network overhead and improve performance.

### Reference from Go SDK (`PrepareBatch` Example):

```go
type MyStruct struct {
    Column1 string
    Column2 int
}

func batchInsert(conn *clickhouse.Conn, data []MyStruct) error {
    batch, err := conn.PrepareBatch(context.Background(), "INSERT INTO my_table (column1, column2)")
    if err != nil {
        return err
    }

    for _, record := range data {
        err := batch.Append(record.Column1, record.Column2)
        if err != nil {
            return err
        }
    }

    return batch.Send()
}
```

### Request 
It would be very useful if Rust SDK has a similar `PrepareBatch` feature in the Rust SDK, allowing for batch inserts that can efficiently handle multiple rows in a single request, improving throughput and minimizing query overhead 🙏

**Comment by serprex** [comment]
How does Inserter not meet your needs?

**Comment by slvrtrn** [comment]
Here's the related `inserter` feature example: https://github.com/ClickHouse/clickhouse-rs/blob/main/examples/usage.rs#L40-L58

**Comment by barkhayot** [comment]
Thanks 🙏

**Comment by loyd** [comment]
The basic `Insert` fits here because you have the whole batch of rows. `Inserter` is useful for (potentially infinite) streams.

**Comment by barkhayot** [comment]
@loyd Thanks! I will try that 🙏
