### ISSUE TITLE
Where is the Pool of connections, and how to limit it.

### ISSUE THREAD

**Issue by rsalmei** [ClickHouse/clickhouse-rs#47]
Hi, I'm trying to migrate https://github.com/suharev7/clickhouse-rs to use yours, but I cannot find where the Pool is.
I want to have some connections always established, and need to keep at least one at all times, i.e. pool_min and pool_max.

Your docs say almost nothing about it, besides that one sentence "Reuse created clients or clone them in order to reuse a connection pool".
Please, care to explain it better? How does a Pool work here?
Thank you.

**Comment by rsalmei** [comment]
I see, thanks. I've never used hyper myself, so I'm not familiar with how it manages Pools. I'll try to take a look sometime.

I wanted pool_min and pool_max just because suharev7's [provides them](https://github.com/suharev7/clickhouse-rs#dns), and I've grown accustomed to using them:
```
pool_min - Lower bound of opened connections for Pool (defaults to 10).
pool_max - Upper bound of opened connections for Pool (defaults to 20).
```
That makes it simple to limit the number of CH connections, while still having some always available.
And yes, I do agree a Semaphore would be more flexible, although the less new code I have to write to port my system, the sooner I could have it done...

Anyway, I like very much your query with .bind() support and the typed .fetch_all(), very cool features!
But it seems I won't be able to migrate any time soon, until I can make sense of the hyper Pools, and develop this min/max limiter...

**Comment by gd87429** [comment]
> It should be noted in docs, I agree and will close the issue after adding it.

I'm also interested. Code example would be super nice.
